### ISSUE TITLE
Replication: add an API to at least list existing replications

### ISSUE THREAD

**Issue by AlexandreToyer** [jaeksoft/opensearchserver#1093]

**Comment by emmanuel-keller** [comment]
### List of replication items

GET http://localhost:8080/services/rest/index/{index_name}/replication

```json
{
  "successful":true,
  "info":"2 item(s) found",
  "items": 
  [ 
    {
    "name":"http://localhost:8080/geo_repl",
    "replicationType":"BACKUP_INDEX",
    "remoteUrl":"http://localhost:8080",
    "remoteIndexName":"geo_repl",
    "secTimeOut":120,
    "isActiveThread":false
    }, 
    {
    "name":"http://localhost:8080/geo_repl2",
    "replicationType":"BACKUP_INDEX",
    "remoteUrl":"http://localhost:8080",
    "remoteIndexName":"geo_repl2",
    "secTimeOut":120,
    "isActiveThread":false
    }
  ]
}
```

### Get one replication item

GET http://localhost:8080/services/rest/index/{index_name}/replication?name={replication_name}

```json
{
  "successful":true,
  "name":"http://localhost:8080/geo_repl",
  "replicationType":"BACKUP_INDEX",
  "remoteUrl":"http://localhost:8080",
  "remoteIndexName":"geo_repl",
  "secTimeOut":120,
  "isActiveThread":false
}
```

### Delete one replication item

DELETE http://localhost:8080/services/rest/index/{index_name}/replication?name={replication_name}

### Create/update a replication item

POST http://localhost:8080/services/rest/index/{index_name}/replication?name={replication_name}
Header: Content-Type:application/json
Pass the parameter of the replication item as JSON in the body. The name will be automatically generated.
```json
{
  "replicationType":"BACKUP_INDEX",
  "remoteUrl":"http://localhost:8080",
  "remoteIndexName":"geo_repl2",
  "secTimeOut":120
}
```

### Run the replication

POST http://localhost:8080/services/rest/index/{index_name}/replication/run()?name={replication_name}

**Comment by AlexandreToyer** [comment]
Documentation: http://www.opensearchserver.com/documentation/api_v2/replication/README.md
