### ISSUE TITLE
Ability to copy indices

### ISSUE THREAD

**Issue by NicoHaase** [jaeksoft/opensearchserver#1315]
Hi there,
we use some highly modified indices that share most settings. On adding a new index, we currently have to copy the settings manually. It would be very nice to have a copy feature that is able to create a new index based on an existing, excluding the result databases

**Comment by AlexandreToyer** [comment]
Hello,

We recently developped APIs for Scheduler and Replication :  

* http://www.opensearchserver.com/documentation/api_v2/scheduler/README.md
* http://www.opensearchserver.com/documentation/api_v2/replication/README.md

This could be useful to you.

Regards,
Alexandre

**Comment by AlexandreToyer** [comment]
This page will explain the process: http://www.opensearchserver.com/documentation/faq/querying/how_to_replicate_and_merge_indexes.md
