### ISSUE TITLE
REST API - More information about Indexes

### ISSUE THREAD

**Issue by adamlonsdale** [jaeksoft/opensearchserver#1323]
Hi,

I'd really appreciate it if we could extend the REST API to provide more comprehensive information about an Index when queried at /services/rest/Index/{{name}}. I would expect this enhancement to allow things such as locations, number of documents, last update time and current status (is it crawling, parsing or idle? 

Thanks

**Comment by adamlonsdale** [comment]
Testing with this so far seems good. I was wondering if there was to be further work undertaken in regards to a GET on the file locations? I assume this would be something within opensearchserver/src/main/java/com/jaeksoft/searchlib/webservice/crawler/filecrawler/FileCrawlerImpl.java that would be called from http://{{server}}/services/rest/crawler/file/repository/{{index name}}/json 
 which returns a list of file locations as well as the type of location (dropbox, swift, FTP, SMB, Local etc.)

**Comment by emmanuel-keller** [comment]
Hi Adam,

There is a few historical API using  /json and /xml prefixes. They still exists, but we are now using new patterns. In the new API, choosing between JSON and XML will be made passing the right header. But don't worry, we will keep the old one active.
I just close this issue, as it is related to the index list.

**Comment by adamlonsdale** [comment]
Hi Emmanuel,

Thanks for your response. I assume there is no GET API for retrieving a list of file locations after looking through the code. Should I create a new issue for this?

Thanks
