### ISSUE TITLE
URL fragments filtering

### ISSUE THREAD

**Issue by a4i** [jaeksoft/opensearchserver#1336]
Web crawler URL filter module let to clean up query strings like JSESSIONID.

At the moment, it only applies to the querystring part of the URL. It would be great have the same functionality applying to the fragment part of the URL.

The HTML Parser let us remove the URL fragment, but it's inconditionaly.

Many frameworks like Angular.js use the fragment part to route URLs without page reloading (hashbang router). So it would be great to be able to apply regexp on this part too.

Regards

**Comment by emmanuel-keller** [comment]
Thanks for your feature request. It has been implemented. It will be officially available in the next release.
If you want, you can test it using the last nightly build (>= build 877) of the v1.5 branch here:
http://www.open-search-server.com/ftp/OpenSearchServer_1.5/

![screen shot 2015-01-08 at 13 05 11](https://cloud.githubusercontent.com/assets/1282276/5662585/5bc2c86a-973b-11e4-96ef-080bd74c7174.png)
