### ISSUE TITLE
Cron Expression Fails

### ISSUE THREAD

**Issue by Bram0** [jaeksoft/opensearchserver#1381]
the Cron expression on a scheduler fails.

it is active, and set for:

seconds: 0
Minutes: 45
Hours: 20
Day of month: ?
month: *
Day of week: FRI
Year: * 

what it does: nothing

what it suppose to do:
File Crawler Start at every Friday at 20:45

OSS 1.5.9

**Comment by AlexandreToyer** [comment]
Hi Bram,

Expression looks good. It should work. Do you get something in logs? Please look at Runtime / Logs and also in the logs of the scheduler. Do you have some other jobs configured on this index or on other index? They may be wrongly configured and cause this job to not run.

Thank you,
Alexandre

**Comment by Bram0** [comment]
Hi Alexandre,

Unfortunately there's no record of the event in the logs... It acts as if it wasn't active at all..

This is the only scheduler on this index. Other indices have schedulers though, but those don't involve this particular index. 

the other indices have schedulers so that one is done crawling it starts the next one. But this is a large index with over 2 million files that doesn't need indexing daily so it should do once a week in the weekend or so. hence I put a cron expression in place to take care of the job.

the run log just says the hourly updates from the other index that is crawling at that moment.

Kind Regards,
Bram de Wit

**Comment by AlexandreToyer** [comment]
Hi Bram,

Did you check the tab "Logs" in the scheduler?

When you edit the job and click "Save", you do not get any error message?

Can you confirm that checkbox "Enabled" is checked?

Thank you,
Alexandre

**Comment by Bram0** [comment]
Hi Alexandre,

Yes I checked the scheduler log, it shows it started on the times I manually started the scheduler, but no error message as to why it did not start on the scheduled time.

When I edit and save there's no error message.

Yes I  can confirm the check box active: enabled is checked. Also the send e-mail on failure is checked and set for my email, however no mail to why it hasn't worked was sent.


Kind regards,
Bram de Wit

**Comment by AlexandreToyer** [comment]
That's really weird because we never experienced this error. Can you send me a screenshot of the edit page of your job?

Thank you,
Alexandre

**Comment by Bram0** [comment]
Sure thing, here’s  a screenshot of the cron job

 

 

Thing aside from this:

 

If I open my browser, go to the searchpage and do a search, say I search “test1234”

If I close the tab, reopen it, it still says “test1234” while if I open other browser it says blank

 

Can I change this somehow so that it always shows blank when opening the searchpage?

 

 

Kind regards,

Bram de Wit

**Comment by AlexandreToyer** [comment]
Hi Bram,

I can not see your screenshot. Can you send it to contact@open-search-server.com?

Regarding the other issue it is the default behaviour for the renderer, last query stays in session. This setting is not configurable for now.

Regards,
Alexandre

**Comment by Bram0** [comment]
Hi Alexandre,

I have mailed you the screenshot.

Regarding the other issue, there is an option I found out.

When using the viewer link, and adding "&query=" behind it, it gives you the blank all the time. That was wat I was looking for.

Kind Regards,
Bram de Wit

**Comment by AlexandreToyer** [comment]
Thank you. For the `&query=` that's true, I should have think about it, sorry!

I saw the screenshot but so far I do not see what is wrong. Could you change the CRON expression for the job to run in a few minutes? We would see if it works with another expression...


Alexandre

**Comment by Bram0** [comment]
Well I just set it to 0 40 9 ? * 5 *

 

Basically every Thursday 9:40AM

 

It runs just fine, so I’ve set it to 0 40 20 ? * 6 * to see if it then runs tomorrow.

 

(although I think FRI should be accepted as well?)

 

If it works it works, and then it’s not much of an issue, I’ll keep you updated on how it goes.

 

 

Kind Regards,

Bram de Wit

**Comment by Bram0** [comment]
Hi,

 

With the FRI option it didn’t work but with digits it did. So I’ll use digits and it works fine, thanks!

 

 

Kind regards,

Bram de Wit

**Comment by AlexandreToyer** [comment]
Hello Bram,

That is really surprising, it should work with `FRI`.

Anyway I'm glad you found a workaround for this issue.

Thank you,
Alexandre
