### ISSUE TITLE
Create a GET API for getting a list of file locations

### ISSUE THREAD

**Issue by adamlonsdale** [jaeksoft/opensearchserver#1393]
I assume there is no GET API for retrieving a list of file locations after looking through the code

**Comment by emmanuel-keller** [comment]
Hi Adam,

We have implemented the API.

- HTTP Method: GET
- URL: http://localhost:9090/services/rest/crawler/file/index/{index_name}

Use the "Accept" HTTP header to select returned format :
- Accept: application/json
- Accept: application/xml

You can test it using the latest nightly build.
http://www.open-search-server.com/ftp/OpenSearchServer_1.5/build-1.5-b909/

Example of JSON result:

```json
{
  "successful": true,
  "info": "2 item(s) found",
  "items": [
  {
    "type": "LOCAL",
    "scheme": "file",
    "path": "/Users/ekeller/Desktop/OSS_demo/medias",
    "enabled": true,
    "withSubDirectory": false,
    "ignoreHiddenFiles": true,
    "delayPerFile": 0
  },
  {
    "type": "LOCAL",
    "scheme": "file",
    "path": "/Users/ekeller/Desktop/TestOCR",
    "enabled": true,
    "withSubDirectory": true,
    "ignoreHiddenFiles": true,
    "delayPerFile": 10
  }
 ]
}
```

**Comment by adamlonsdale** [comment]
Thanks for this. I will implement it into our side ASAP. I'll wait for a version 2 nightly build as thats what I've been testing with.
