### ISSUE TITLE
Let the parsing API decides wich parser to use

### ISSUE THREAD

**Issue by a4i** [jaeksoft/opensearchserver#1412]
To parse a document via the API, I have to specify wich parser to use.

This can be problematic, because I don't know what content-types OSS parsers support. I have to guess the content-type by my own as well (and maybe my tools to find the content-type are much poor than the OSS ones).

Is it possible to have a new API service to upload a document for parsing, without to have to specify its content-type, and let OSS guess it (like it does with the filesystem crawler, ie).

With this solution I have a unique point where to control parsing and content-types strategies.

Furthermore, it would be nice that the /services/rest/parser service returns the supported mimetypes by for each parser.

regards

**Comment by emmanuel-keller** [comment]
We made few changes in the new Parser API.

GET returns the default extensions and the default mime types supported by the parser.

    curl -XGET http://localhost:9090/services/rest/parser/eml

```json
{
  "name": "EML",
  "fields": [
    "parser_name",
    "email_display_from",
    "email_display_to",
    "email_display_cc",
    "email_display_bcc",
    "email_conversation_topic",
    "subject",
    "content",
    "email_sent_date",
    "email_received_date",
    "email_attachment_name",
    "email_attachment_type",
    "email_attachment_content",
    "htmlSource",
    "lang"
  ],
  "file_extensions": [
    "eml"
  ],
  "mime_types": [
    "message/rfc822"
  ]
}
``` 

A new PUT API let's use the mime magic features.

It is possible to upload a file, or pass the path to the file.

Uploading the file:

     curl -XPUT \
    --data-binary @rulesofcompetitions.pdf \
    http://localhost:9090/services/rest/parser?name=email.eml&type=message/rfc822

The **name** parameter and the **type** parameter are optional. The name is useful in the case of ambiguous mime detection. EML files are detected as text/plain, but if the name of the file is passed, the API will choose the EML parser by checking the extension.

Using a path (local to the server):

    curl -XPUT \
    http://localhost:9090/services/rest/parser?path=/users/ekeller/email.eml
