### ISSUE TITLE
Crawl issue - robots.txt error / not allowed

### ISSUE THREAD

**Issue by jv828642** [jaeksoft/opensearchserver#1554]
Hi,
We're facing an issue with opensearchserver. When crawling a website, we don't see any documents get indexed. In the oss.log we found the following error logging:
11:50:28,997 ERROR: root - Circular redirect to 'https://<url>/NL/nl/robots.txt'
11:50:28,998 ERROR: root - com.jaeksoft.searchlib.crawler.web.spider.HttpAbstract.getRedirectLocation(HttpAbstract.java:222)
We've recently upgraded to v1.5.13, comming from a previous version v1.5.8. Though the updated version does not seem to be causing the issue, since we reverted the version and the problem still occurs.
We have set the following pattern for web crawling 'https://url/*'. This does not automatically resolve the robots.txt. Using another random website url does. Even using the search does not give a result. Even no (error) logging?
A manual crawl gives us the following output:
Robots.txt status: Error
Fetch status: Not allowed
We've even enabled HTTP clien logging with the following output:
[DEBUG] PoolingHttpClientConnectionManager - Connection manager shut down
[DEBUG] PoolingHttpClientConnectionManager - Connection manager is shutting down
[DEBUG] RequestAddCookies - CookieSpec selected: best-match
[DEBUG] RequestAuthCache - Auth cache not set in the context
[DEBUG] PoolingHttpClientConnectionManager - Connection request: [route: {s}->https://url:443][total kept alive: 0; route allocated: 0 of 2; total allocated: 0 of 20]
[DEBUG] PoolingHttpClientConnectionManager - Connection leased: [id: 0][route: {s}->https://url:443][total kept alive: 0; route allocated: 1 of 2; total allocated: 1 of 20]
[DEBUG] MainClientExec - Opening connection {s}->https://url:443
[DEBUG] HttpClientConnectionOperator - Connecting to url/10.169.54.165:443
[DEBUG] HttpClientConnectionOperator - Connection established 10.169.54.165:36400<->10.169.54.165:443
[DEBUG] MainClientExec - Executing request GET /robots.txt HTTP/1.1
[DEBUG] MainClientExec - Target auth state: UNCHALLENGED
[DEBUG] MainClientExec - Proxy auth state: UNCHALLENGED
[DEBUG] headers - http-outgoing-0 >> GET /robots.txt HTTP/1.1
[DEBUG] headers - http-outgoing-0 >> Host: url
[DEBUG] headers - http-outgoing-0 >> Connection: Keep-Alive
[DEBUG] headers - http-outgoing-0 >> User-Agent: OpenSearchServer_Bot
[DEBUG] headers - http-outgoing-0 >> Accept-Encoding: gzip,deflate
[DEBUG] headers - http-outgoing-0 << HTTP/1.1 301 Moved Permanently
[DEBUG] headers - http-outgoing-0 << Location: /GB/en/robots.txt
[DEBUG] headers - http-outgoing-0 << Content-Length: 0
[DEBUG] headers - http-outgoing-0 << Date: Wed, 06 May 2015 07:07:46 GMT
[DEBUG] headers - http-outgoing-0 << Server: <Server>
[DEBUG] MainClientExec - Connection can be kept alive indefinitely
[DEBUG] DefaultRedirectStrategy - Redirect requested to location '/GB/en/robots.txt'
[DEBUG] PoolingHttpClientConnectionManager - Connection manager is shutting down
[DEBUG] PoolingHttpClientConnectionManager - Connection manager shut down
[DEBUG] PoolingHttpClientConnectionManager - Connection [id: 0][route: {s}->https://url:443] can be kept alive indefinitely
[DEBUG] PoolingHttpClientConnectionManager - Connection released: [id: 0][route: {s}->https://url:443][total kept alive: 1; route allocated: 1 of 2; total allocated: 1 of 20]
[DEBUG] PoolingHttpClientConnectionManager - Connection manager is shutting down
[DEBUG] DefaultManagedHttpClientConnection - http-outgoing-0: Close connection
[DEBUG] DefaultManagedHttpClientConnection - http-outgoing-0: Close connection
[DEBUG] PoolingHttpClientConnectionManager - Connection manager shut down
[DEBUG] PoolingHttpClientConnectionManager - Connection manager is shutting down
We're not exactly sure what is going wrong here. The robots.txt is accessible through our browser. Any hints on what might be causing the circular redirect?
Kind regards,
Joris Vanleene
PS: I've not included any production url's. If needed, plz PM me for details.

**Comment by jv828642** [comment]
We know what is going wrong..
The version upgrade to v1.5.13 is causing the web crawl to not pick up our robots.txt.
com.jaeksoft.searchlib.crawler.web.process.WebCrawlThread has been modified (see lines below) due to issue GH-716. The change (passing a false for followRedirects, in stead of true) makes it impossible to find a robots.txt (which is, as in our case, redirected with a 301 redirect from /robots.txt to /GB/en/robots.txt).
httpDownloaderRobotsTxt = new HttpDownloader(propertyManager
.getUserAgent().getValue(), false,
propertyManager.getProxyHandler());
Can someone elaborate on why this is changed, or why this change is needed? Or might this be a bug in the software?
Can this be resolved (via configuration) in any way? Otherwise we won't be able to upgrade to newer versions in the future.

**Comment by emmanuel-keller** [comment]
Ok, thanks for your reminder.

Handling redirection or not is not really clear.

We had a look at how Google handle that:
https://developers.google.com/webmasters/control-crawl-index/docs/robots_txt

It seems that GoogleBot follows the redirection. Let's go back to this behavior. Give me few minutes ...

**Comment by emmanuel-keller** [comment]
A nightly build with the fix is available here:
http://download.opensearchserver.com/OpenSearchServer_1.5/build-a0564ca/
