### ISSUE TITLE
Faulty cookie support with HttpClient

### ISSUE THREAD

**Issue by chrishughesspotify** [jaeksoft/opensearchserver#1674]
14:59:58,240 WARN: org.apache.http.client.protocol.ResponseProcessCookies - Invalid cookie header: \"Set-Cookie: logged_in=no; domain=....; path=/; expires=Tue, 20 Nov 2035 14:59:58 -0000; secure; HttpOnly\". Invalid 'expires' attribute: Tue, 20 Nov 2035 14:59:58 -0000

**Comment by attacomsian** [comment]
Hey, 

do you have any workaround for this issue? I am trying to download files from github but it is throwing following error: 

```
Invalid cookie header: "Set-Cookie: logged_in=no; domain=.github.com; path=/; expires=Sat, 10 May 2036 10:50:44 -0000; secure; HttpOnly". Invalid 'expires' attribute: Sat, 10 May 2036 10:50:44 -0000
Invalid cookie header: "Set-Cookie: logged_in=no; domain=.github.com; path=/; expires=Sat, 10 May 2036 10:50:44 -0000; secure; HttpOnly". Invalid 'expires' attribute: Sat, 10 May 2036 10:50:44 -0000
```

**Comment by emmanuel-keller** [comment]
It seems to be related to this issue:
https://issues.apache.org/jira/browse/HTTPCLIENT-1640
