### ISSUE TITLE
Property 'reportSet' not found on QueryReportsController

### ISSUE THREAD

**Issue by emmanuel-keller** [jaeksoft/opensearchserver#1687]
Property 'reportSet' not found on type com.jaeksoft.searchlib.web.controller.report.QueryReportsController

**Comment by Ansaldos** [comment]
Dear Emmanuel!

I facing with this issue on the current version.

**Comment by emmanuel-keller** [comment]
v1.5.13 contains the bug. 

You can use our nighlty build v1.5.14 :
http://download.opensearchserver.com/OpenSearchServer_1.5/
