### ISSUE TITLE
OSS local files crawl error

### ISSUE THREAD

**Issue by shahg2** [jaeksoft/opensearchserver#1688]
Dear all,
Any body plz let me know i have thousands of files that are indexed now through localfiles crawl template. But a big issue, in files where there are spaces they are not opening while clicking on the hyperlink, even open folder is not working. its hard for me to rename the files and remove spaces.
in files and folders where are no spaces they are opening fine upon clicking.
Plz give me a suggestion, really stuck.
Thanks.

**Comment by emmanuel-keller** [comment]
Hi,

I just made some test. The spaces are encoded as %20 in the HTML source code which seems to be correct. Does your Internet browser generates any error in its console ?

**Comment by shahg2** [comment]
Hi, really thanks for the reply.
Yes %20 is filled with spaces in html. But all browsers show error, page can not be displayed. Where there are no spaces in folders and files paths the files downloads and open directly without error.
I tried putting \\atcokb\test<file:///\\atcokb\test>, //atcokb/test   in crawler locations path, but didn’t work.
Also When I press viewer to view files, only pdf files show in viewer whether there is a space or without space in file and folder names.
But docs, rtf, excel and power point files  not displaying in viewer even.
also if there is a space in file name or folder name Open Folder option is not working. (open folder option is only working for the files in which there are no spaces.)

Plz show some light in the tunnel. Waiting for your kind reply.
Regards

Tufail Shah
System & Network Administrator

Al Tamimi & Company
Dubai International Financial Centre
Registered with the DFSA

T: +971 4 364 1641   F: +971 4 364 1777

www.tamimi.com

Bahrain   ▪   Egypt   ▪   Iraq   ▪   Jordan   ▪   Kuwait   ▪   Oman   ▪   Qatar   ▪   Saudi Arabia   ▪   UAE

**Comment by shahg2** [comment]
Furthermore for your kind information in the browser when I manually remove %20 to a normal space. the files open successfully.

**Comment by emmanuel-keller** [comment]
Ok. Can you please edit the Renderer and just check the "URL decode" checkbox for the fields "Title" and "Filename".

It should work now.

![screen shot 2015-12-22 at 11 51 17](https://cloud.githubusercontent.com/assets/1282276/11953700/821b7e52-a8a2-11e5-9082-ee33726d3e4a.png)

**Comment by shahg2** [comment]
A big big thanks. Its indeed a Christmas gift. It worked like a charm . I was literary struggling from last one week. You are a star.
Once last thing how can I remove Open Folder and Viewer option. As viewer is a good option but only works for pdf files .doc files are not opening in viewer.
Thanks.


Our Firm<http://www.tamimi.com/en/section/our-firm> | Our Practices<http://www.tamimi.com/en/section/our-practices> | Our Sectors<http://www.tamimi.com/en/section/our-industries> | Our Offices<http://www.tamimi.com/en/section/our-offices>

<http://feedback.tamimi.com/EmailMarketing/ClickThroughHandler.aspx?link=%3ca+href%3d%22http%3a%2f%2fwww.linkedin.com%2fcompany%2fal-tamimi-%26-company%22%3ehttp%3a%2f%2fwww.linkedin.com%2fcompany%2fal-tamimi-%26-company%3c%2fa%3e&nid=abbdcaba-9bb1-48d3-b48>[cid:7cd30f5ac2ca4ac78e3830dda9d89d25]<http://www.linkedin.com/company/al-tamimi-&-company>      [cid:8eaf7b5f6fe2487080d64483df6d7a71]



Email Confidentiality Notice
The information in this email is private, confidential and may be covered by legal professional privilege or other legal or attorney/client privilege. It is intended solely for the person to whom it is addressed. If you are not the intended recipient please telephone or email us immediately and remove it from your system. If you are not the intended recipient you may not copy it or use it for any purpose nor disclose the contents to any other person.

**Comment by emmanuel-keller** [comment]
> Once last thing how can I remove Open Folder and Viewer option.

Just remove the last field from the Renderer. The one with the "Tools" widget.

**Comment by shahg2** [comment]
Really simple and intuitive interface. Thanks for your kind help. All fixed now. OSS is excellent.
One last thing I was wondering daily we are creating new files, what about them, if I run crawler again it will recrawl all again. Is there any method or incremental crawler so to avoid the prvious crawled files.
Much appreciate.



Tufail Shah
System & Network Administrator

Al Tamimi & Company
Dubai International Financial Centre
Registered with the DFSA

T: +971 4 364 1641   F: +971 4 364 1777

www.tamimi.com

Bahrain   ▪   Egypt   ▪   Iraq   ▪   Jordan   ▪   Kuwait   ▪   Oman   ▪   Qatar   ▪   Saudi Arabia   ▪   UAE
