### ISSUE TITLE
Disabling link detection

### ISSUE THREAD

**Issue by djtak47** [jaeksoft/opensearchserver#1689]
Hi,

We are using OSS now for some weeks to crawl a good amount of websites, we have now around 6 Million Pages in our URL database. 

We are Parsing then the sites with some special NLP parsers to detect if its a profile page or not.
This results in a list of urls we get back with just profile urls. 

Now My Questions:
1. How can we achieve it to crawl only the Profile Urls, but not make OSS follow other pages?
     1. We were thinking about creating a sitemap and submit it to a new index in oss but, how to prevent oss to follow links?     

2. We are doing the Main Extraction of the Content Right now trough the API, let me explain:
    1. OSS Performs a crawl on the complete Website eg. http://website1.com/*
    2. We get the HTMLContent trough die API , read the Content With PHP and extract certian Informations with XPATH to detect if its a profile or not, and decide which information should be extracted. 

My Question: is there a better solution to this ? Is it possible to extract information with xpath or something else, we checked but saw only xpath for XML and the selenium implementation seems to be only for performing actions but not content extraction

Thanks for your support !!!

**Comment by emmanuel-keller** [comment]
> We were thinking about creating a sitemap and submit it to a new index in oss but, how to prevent oss to follow links?

If you provide a sitemap, OSS will first inject the URLs found in the sitemap in its URL database.

Of course, OSS will detect the links and try to add them. So, we should provide a way to disable the link detection. So, this is a feature request. I just renamed this issue.

> Is it possible to extract information with xpath or something else

Currently, we have a regular expression extractor. It is located in FieldMap panel of the HTML Parser (panel Schema/Parser List). This regexp is applied to the HTML source.  It is then copied to any field of your schema.

**Comment by djtak47** [comment]
Hi Emmanuel ,

Thanks for the Reply. 

For the First issue: If iam correct OSS is running on Nutch. Nutch has the ability to disable Following Links // FYI.

Second issue: I saw the Regex possibility but we had the problem that we can not define patterns per Site (Url) Just for the Complete Index. Also Xpath makes life much easier extracting content than Regex,

Would be really nice if it was possible to Define Xpath Extrators for specific Urls.

Thank you & Merry Christmas :)

**Comment by emmanuel-keller** [comment]
> For the First issue: If iam correct OSS is running on Nutch. Nutch has the ability to disable Following Links 

OpenSearchServer's web crawler is not based on Nutch. We built this feature from scratch.

> Second issue: I saw the Regex possibility but we had the problem that we can not define patterns per Site (Url) Just for the Complete Index. Also Xpath makes life much easier extracting content than Regex,

You can use one index per web site, that way you can have different patterns.

The feature has been implemented. You can download the last nightly build of OpenSearchServer v1.5.14 here:
http://download.qwazr.com/latest/

![screen shot 2015-12-27 at 21 59 10](https://cloud.githubusercontent.com/assets/1282276/12012209/335500f2-aceb-11e5-8dbf-4d99de347545.png)

**Comment by djtak47** [comment]
hi Emmanuel, Thank you very much, thats awesome. I will install it tomorrow.

Regarding :  "You can use one index per web site, that way you can have different patterns."

We did not work in this way,we have only one index. And I dont think it makes sense if you have Hundrets of Domains to crawl to have hundrets of indexes? Especially if you retrieve the data trough the api afterwards?

Really appreciate your help!
