### ISSUE TITLE
Ignored "Number of suggestion" for auto-completion

### ISSUE THREAD

**Issue by epiniguin** [jaeksoft/opensearchserver#1697]
Hi!
The parameter "Number of suggestion" of the auto-completion is ignored.
In any case 10 suggestions are used by default in the renderer.

**Comment by emmanuel-keller** [comment]
It was a bug in the v1 autocomplete API which set a default value of 10. It has been fixed (in last v1.5.14 build) and now it uses the configured value.

**Comment by epiniguin** [comment]
Thank you, Emmanuel!
