### ISSUE TITLE
org.apache.cxf.interceptor.Fault, Tomcat 7.0.53, when starting crawl

### ISSUE THREAD

**Issue by telethonic** [jaeksoft/opensearchserver#1729]
Hi,

I'm trying to run a small crawl using the php client, using code that worked before.

This is using OpenSearchServer v1.5.13 - build 2b6dfa4d90.

Now I'm getting a Tomcat java exception (see attached screenshot and full HTML file of the error)
(edit: uploaded a 2nd screenshot showing the bottom part, .HTML was not supported)

This is the relevant bit of my PHP code:
(all works ok up to the start, the "start response" contains the HTML error page)

Is there something obvious I'm missing?

thanks :)

```
            //
            // get crawler status
            //
            $request = new OpenSearchServer\Crawler\Web\GetStatus();
            $request->index($index_name);
            $response = $oss_api->submit($request);
            
            $json = $response->getJsonValues();
            
            $now = date("Y-m-d H:i:s");
            print "$now - crawler status [" . print_r($json, true) . "]";
            
            //
            // if not running, start it
            //
            if ($json->info == "STOPPED") {
              print "  crawler is not running\n";
              
              $request = new OpenSearchServer\Crawler\Web\Start();
              print "  requesting start, index [$index_name]\n";
              
              $request->index($index_name);
              $response = $oss_api->submit($request);
              print "  start response [" . print_r($response, true) . "]\n";
              
              $json = $response->getJsonValues();

              $now = date("Y-m-d H:i:s");
              print "$now - crawler start return [" . print_r($json, true) . "]";
              
              if ($json->info != "STARTING") {
                print "Error starting crawler\n";
              }
            }
```            

![exception](https://cloud.githubusercontent.com/assets/13541386/13074661/45125622-d4a6-11e5-9620-642a4403336d.png)

![exception2](https://cloud.githubusercontent.com/assets/13541386/13074698/87fff1e2-d4a6-11e5-9cf9-44fc9b23a4fb.png)

**Comment by emmanuel-keller** [comment]
We just fixed the bug. The nightly build which includes the fix is available here:
http://download.opensearchserver.com/OpenSearchServer_1.5/build-d01e6e5/

A workaround exists if you want to keep the current stable version (v1.5.13). Just pass the parameter "?once=false" on your HTTP/REST call.
