### ISSUE TITLE
Add and Remove sitemaps from index trough the REST API / php client?

### ISSUE THREAD

**Issue by djtak47** [jaeksoft/opensearchserver#1755]
Is there a way to do this? 

Thanks for your support.

**Comment by emmanuel-keller** [comment]
Currently this API is not available. We start working on this.

**Comment by emmanuel-keller** [comment]
We will the following API:

/services/rest/index/{index_name}/crawler/web/sitemap

**Comment by djtak47** [comment]
Thanks, awesome!

**Comment by Tetraa** [comment]
It's work now

You can test this here :
http://www.open-search-server.com/ftp/OpenSearchServer_1.5/build-b034596/

The documentation is here: http://www.opensearchserver.com/documentation/api_v2/WEB_crawler/sitemap/README.md
 
Have fun.

let me know if everything work as you want.

**Comment by djtak47** [comment]
Hi, thank you!
If the features are working as descriped in the documentation, its what i wanted / needed. Thank you very much. Ill give you feedback when i have implemented it.

**Comment by djtak47** [comment]
Hi, we upgraded the .deb version as described here: http://www.opensearchserver.com/documentation/installation/upgrading_opensearchserver.md

we used the deb version here : 
http://www.open-search-server.com/ftp/OpenSearchServer_1.5/build-b034596/opensearchserver-1.5.14-SNAPSHOT-febb4bd.deb

it seems that the service is not availible because its returning a 404 when i 

curl -XGET http://myossinstance/services/rest/index/theredpages.de_broad_crawl/crawler/web/sitemap?login=username&key=key

Returns 404

Thanks for your help.
