### ISSUE TITLE
Crawler - API to delete URL browser

### ISSUE THREAD

**Issue by fmassiera** [jaeksoft/opensearchserver#1773]
Using API only, if we want to have a fresh new crawler from an old one, it would be necessary to be able to delete URL browser via API (actually, the only way to do it, is going to Crawler => Web => Url Browser and delete there).

**Comment by emmanuel-keller** [comment]
We have started the implementation.

@Tetraa, some hints:

The feature should call the "DeleteAll" function of the URLBrowser.
Here is the expected prototype:

```java
@DELETE
	@Produces({ MediaType.APPLICATION_JSON, MediaType.APPLICATION_XML })
	@Consumes({ MediaType.APPLICATION_JSON, MediaType.APPLICATION_XML })
	@Path("/urls")
public CommonResult truncateUrls(@PathParam("index_name") String use, @QueryParam("login")
    String login, @QueryParam("key") String key);
```

The prototype should be added here:
https://github.com/jaeksoft/opensearchserver/blob/master/src/main/java/com/jaeksoft/searchlib/webservice/crawler/webcrawler/RestWebCrawler.java

And, as usual, the implementation goes here;
https://github.com/jaeksoft/opensearchserver/blob/master/src/main/java/com/jaeksoft/searchlib/webservice/crawler/webcrawler/WebCrawlerImpl.java

**Comment by Tetraa** [comment]
okay i start this now !
