### ISSUE TITLE
Schéma/Crawler - parameter crawlDate

### ISSUE THREAD

**Issue by fmassiera** [jaeksoft/opensearchserver#1775]
It used to be to have a crawlDate parameter in order to have indexed time. Unfortunatly it doesn't seem to work anymore (OpenSearchServer v1.5.14-SNAPSHOT - build e9515c9750)

**Comment by emmanuel-keller** [comment]
The crawlDate was wrongly linked in the fieldmap.
The crawlDate is not available in the WebCrawler. You can use the "when" field in replacement.
