### ISSUE TITLE
file crawler / java heap space 

### ISSUE THREAD

**Issue by kileurf** [jaeksoft/opensearchserver#1787]
Hello,

for an enterprise project I need to index a directory containing more than 800 000 files. I choosed to use OSS for that.

I create an new file crawler, and take the path of my directory, when i click on check a see the sub-directories.

I have a probleme when the crawler arrive on certain directories they create errors (java heap space)

I send you a screen of my startup.bat

thanks in advance
Alexis Bulteel
![2016-05-11_120733](https://cloud.githubusercontent.com/assets/10498643/15317237/e8c4110e-1c20-11e6-97f9-ddd9a448ab62.png)

**Comment by emmanuel-keller** [comment]
Hi Alexis,

The memory is the issue. I see that you set the memory parameters both in JAVA_OPTS and CATALINA_OPTS. You should choose JAVA_OPTS only. In your current setup I am not sure which one is used (2GB or 5GB). 

To be sure, you can check which is the effective size in web interface of OSS, in the tab panel /Runtime/System.

**Comment by kileurf** [comment]
Hello,

I tried with the both, for the moment the memory in /Runtime/System is 2GB, but before I tried with 5Gb in JAVA_OPTS but the problem was the same.

So, I don't know if the problem is a memory problem or a file problem.

Have you an idea ?

Regards,
Alexis Bulteel

**Comment by Mojster** [comment]
For me it solve the problem with readjusting the heap size.

I think your problem is with setting the initial and max size to the same value.
The most ergonomically is to set the heap size assuming you have 4G of RAM:
```
#ergonomics algorithm
Initial heap size = 4096M/64 = 64M
Maximum heap size = 4096M/4 = 1024M
```
Off course you can raise it, if needed.
