### ISSUE TITLE
Slovene Lemantization

### ISSUE THREAD

**Issue by Mojster** [jaeksoft/opensearchserver#1822]
I found in the documentation page, that OSS supports 17 languages.
Is there a possibility that you would add also Slovene (Slovenia) language. Certainly I would help and provide the necessary language files.

**Comment by emmanuel-keller** [comment]
Hi,

It seems that a Slovene dictionary is available here:
https://cgit.freedesktop.org/libreoffice/dictionaries/tree/sl_SI

You may use the **sl_SI.aff** and **sl_SI.dic** files with the Hunspell stem filter provided in OSS.

![screen shot 2016-08-09 at 14 30 17](https://cloud.githubusercontent.com/assets/1282276/17516313/e2c8559e-5e3d-11e6-9d6d-aa76969ab7de.png)

**Comment by Mojster** [comment]
Hi,

do I need any extra adjustments that this one is used or this is it?
This is pretty simply compared to SOLR.
