### ISSUE TITLE
Render -> Authentication disabled -> still getting Bad credentials

### ISSUE THREAD

**Issue by Mojster** [jaeksoft/opensearchserver#1828]
Hello again.

I've set in my Render template Authentication to "No authentication". 
If I press the "View" button I can try searching in new tab. So this is my URL to work with.

Now I've created a new user "anonymous" and added privileges to my "index" for "Index: query the index".
Afterwards I've replaced the login and the key parameter in my previous URL and run it in private window.
Now I'm getting:
`<entry key="Status">Error</entry>
<entry key="Exception">
com.jaeksoft.searchlib.web.ServletException: com.jaeksoft.searchlib.SearchLibException: Bad credential
</entry>`

I need a public search and would be great if I could use the Render template, because it has a lot of options and it's easy to use.

If you could help me further or give me so direction, I would be really grateful.

Regards,
Mojster

**Comment by Mojster** [comment]
It's 4 months since I've asked this.
And now this is the last problem that's keeping me from production.

Could you please advise me further.

Thanks,
Mojster

**Comment by emmanuel-keller** [comment]
Hi Mojster,

I just take the ticket. Doing some test. Can you confirm you are using the last release (v1.5.14) ?

**Comment by Mojster** [comment]
I've accidentally closed it. My mistake.

Here's my version:
OpenSearchServer v1.5.14 - build d0d167ef10

**Comment by Mojster** [comment]
Found Reopen.

**Comment by Mojster** [comment]
I'll also try to make my way through this.
With your help, I've managed to compile & run local code.
Also I've imported maven project to Eclipse.

Can you advice me further please. I'm struggling with debugging it. What are you using for running and debugging on the development copy.

**Comment by Mojster** [comment]
Just found in the API documentation:
_As soon as one user gets created, every API call requires passing both a login and an API key._

So I erased all users and tried it again in the renderer and it works without a user & key in the URL.

So I'm closing this issue.
