### ISSUE TITLE
Custom build and run problems

### ISSUE THREAD

**Issue by Mojster** [jaeksoft/opensearchserver#1846]
I've tried to compile code from git on my own.
I had a few problems, which are mentioned in #1829.
1.)
Now when I replace jar & war in current working installation on Windows and I get following error:
`
PS D:\Programs\opensearchserver> .\start.bat
Exception in thread "main" com.github.jankroken.commandline.domain.UnrecognizedSwitchException: class com.jaeksoft.searc
hlib.Server$Arguments: Doss.externalparser.classpath=D:\Programs\opensearchserver/lib/ext/*
        at com.github.jankroken.commandline.domain.OptionSet.consumeOptions(OptionSet.java:43)
        at com.github.jankroken.commandline.CommandLineParser.parse(CommandLineParser.java:39)
        at com.jaeksoft.searchlib.Server.start(Server.java:124)
        at com.jaeksoft.searchlib.Server.main(Server.java:132)
PS D:\Programs\opensearchserver>
`

2.)
I've also tried to import project into Eclipse as Maven project. After importing I've have some errors in pom. 
> Missing artifact com.sun:tools:jar:1.7.0

Also it did not cane through the "maven install" in eclipse. But after I configured JRE to the one in JKD maven found tool.jar. But there is the this error present in pom.xml.
I'm using java 1.8.112 X64.

Can you advise me further.
Thanks in advance.

**Comment by Mojster** [comment]
The dependency for tools.jar is in simple-odf. If this is for any help.

**Comment by emmanuel-keller** [comment]
The rpm package is missing.

Ok, I will fix that in the documentation.

Please find the exact sequence:

```
mvn -Dgpg.skip=true package clean package rpm:attached-rpm
ant clean dist dist-src
```

This is exactly how we build OpenSearchServer on our jenkins. Here is an example of today's build:
https://www.open-search-server.com/jenkins/job/OpenSearchServer_1.5/1173/console

**Comment by Mojster** [comment]
Thanks for the quick answer.
For gpg skip command for windows must be in quotation mark:
`mvn '-Dgpg.skip=true' package clean package rpm:attached-rpm`

Now I get this note:
` Cannot run program "rpm"`

Are you deweloping on windows? Can you suggest any rpm programs.
Otherwise I'll do my research.

**Comment by emmanuel-keller** [comment]
The RPM package are build on linux using the rpm binary
 I just update the build.xml and make the rpm generation optional.
It should go until the end now.

**Comment by Mojster** [comment]
Thanks.
It's working like a charm.

Appreciate your quick response.
