### ISSUE TITLE
How to configure joined/multi index

### ISSUE THREAD

**Issue by Mojster** [jaeksoft/opensearchserver#1847]
Hello.
I'm recently asking a lot of questions. This is because I'm pushing OSS slowly to production.

I have a lot of sites, which needs to be indexed once a month & a site with news, which should be indexed once a day.
I ran into an article/post that stated I should use for this two indexes and joined them in a third one.

Is this the best way?
Could you please advise me further how to configure this.

**Comment by Mojster** [comment]
Just found in the documentation how to merge indexes.
There problem is that "Merge index" option does not exist anymore in the Sheduler part.

Is this a known bug?
Lower in the comments was this reported 8 and 2 months ago.

**Comment by Mojster** [comment]
Found that this functionality was removed with the resolving of task #1659 in February 2016.
Also found an open Issue regarding this: #1840.

**Comment by Tom-Scholes** [comment]
Hi Mojster,

We have a set up with mutliple indexes but do not use merging to run a query across them, this may be a way to get what you are after.

You can set up a multi-index as a new index (not sure what release this was made available in but latest builds have it). Then add the indexes you need to run queries across into this multi-index, this is done in the Runtime>Index tab.
![image](https://cloud.githubusercontent.com/assets/13853958/22254181/c48f5900-e24b-11e6-935f-35bd69f87a23.png)
Searches will then run across all the indexes you add to the multi-index.

We have a large amount of file crawlers that take up a couple of hundred GB of index space, it was not possible to use the merge feature in the usual way so we use this set up instead.

One point to note, the indexes that we have in our mutli-index are not active. They are replicated from other servers that are actually doing the file crawls. I'm not sure if using this type of setup would give you any issues if the indexes are busy crawling.

Hope that is of some help.

Tom

**Comment by Mojster** [comment]
Tom thanks, this has joined our indexes and the search is working properly.
This should be then fixed in the OSS documentation.

On the multi-index the is no default configuration for the autocomplete, so I've copied configuration from "web crawler" template.


Now with multi-index, I've one new problem there is no host field in the Schema. I'm using this as a facet.
Have you any idea hot to set this up.

**Comment by Tom-Scholes** [comment]
Hi Mojster,

We use that field to narrow down searches to specific file servers.

I think you will need to add it into the schema on the multi-index. The image below shows where to add the host field into the schema. We left the values of the field at the defaults and added it in.
![image](https://cloud.githubusercontent.com/assets/13853958/22340589/db731f8a-e3e5-11e6-82e6-f3146e182cfd.png)
Once that is done, you will also need to add it into the crawler under field mapping. Use the drop down boxes to find it and link it to the same field then click 'Add'
![image](https://cloud.githubusercontent.com/assets/13853958/22340657/11dc1bee-e3e6-11e6-895d-7a09514afa52.png)
This is the location but for the file crawler, should be the same for Web but we don't use that.

Also worth noting that we are using repository as an additional field as well, I don't think you will need that for your setup though.

Hope that is helpful.

We have been unable to get the auto-complete working on our setup, I may have a try at this at some point.

Regards
Tom

**Comment by Mojster** [comment]
Tom thanks again. Your setup work perfectly under Web crawler.

For the autocompleter just go under Schema and set it up.
![autocomplete](https://cloud.githubusercontent.com/assets/20921028/22371475/94b361ba-e497-11e6-93de-c8d1112cb828.png)
After that I've just selected it in Renderer. This is set up by default for Web index, but not for multi index.

Hope I could help a bit,
Mojster

**Comment by Mojster** [comment]
Closing. Toms answer was good enough for me.
