### ISSUE TITLE
CamelCase filter/tokenizer

### ISSUE THREAD

**Issue by TudorCretu** [jaeksoft/opensearchserver#1878]
Is there anyway we could handle the indexing of CamelCase names? For example, in MoinMoin wiki a new page is created by simply writing a CamelCase and that it remains its title. I want to be able to index the pages so that a page titled "GraduateScheme" will be found if I search for "Graduate" or "Scheme". Is there any filter or tokenizer able to help me, or is any possibility to create a filter of my own to handle it?

Thank you very much!

**Comment by TudorCretu** [comment]
I solved it by using the RegularExpressionFilter and this regex: 

> ([A-Z]?[a-z0-9]+)+?

Thank you!

**Comment by emmanuel-keller** [comment]
Thanks for sharing you experience !!
